apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: TaskMaster
type: Opaque
stringData:
  OAUTH_CLIENT_ID: u8vpP8lcTQLURxk8itbLvY4pySoa
  OAUTH_CLIENT_SECRET: REeS1LgzdyZfPmaIXloiNor3cMwa
