apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-nfc
  labels:
    app: consumer-nfc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-nfc
  template:
    metadata:
      labels:
        app: consumer-nfc
    spec:
      containers:
        - name: consumer
          image: /consumer-nfc:latest
          command: ["python"]
          args: ["consumer_nfc.py"]
          envFrom:
            - configMapRef:
                name: auth-config
